import { chromium } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '@common/test-utils';
import { IStorageStateOptions } from './types';

const logger = new Logger();

/**
 * Generalized replacement for the old single-role auth.setup.ts: logs in
 * once per role and saves storageState to <authDir>/user-<role>.json so
 * Playwright projects can pick it up without re-authenticating per test.
 *
 * Each app provides its own `performLogin` steps (selectors differ per app)
 * and calls this from its own auth.setup.ts, once per role it supports.
 */
export async function createStorageState(options: IStorageStateOptions): Promise<string> {
  const { appName, role, loginUrl, credentials, authDir, performLogin, headless = false, timeoutMs = 120000 } =
    options;

  if (!credentials.username || !credentials.password) {
    throw new Error(
      `Missing credentials for ${appName}/${role}. Set the role's username/password env vars before running auth:setup.`
    );
  }

  fs.mkdirSync(authDir, { recursive: true });
  const authFile = path.join(authDir, `user-${role}.json`);

  logger.info(`[${appName}] Starting storageState setup for role "${role}"`);

  const browser = await chromium.launch({ headless });
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    await page.goto(loginUrl, { timeout: timeoutMs });
    await performLogin(page, credentials);
    await context.storageState({ path: authFile });
    logger.info(`[${appName}] Saved storageState for role "${role}" -> ${authFile}`);
    return authFile;
  } finally {
    await context.close();
    await browser.close();
  }
}

/**
 * Resolve the storageState file for a role, if it has already been
 * generated by createStorageState(). Returns undefined when missing, so
 * callers can fall back to an unauthenticated context instead of crashing.
 */
export function resolveStorageState(authDir: string, role: string): string | undefined {
  const authFile = path.join(authDir, `user-${role}.json`);
  return fs.existsSync(authFile) ? authFile : undefined;
}
